import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const poppins = Poppins({
// 	subsets: ["latin"],
// 	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// 	display: "swap",
// });

const poppins = localFont({
	src: [
		{
			path: "../../public/font/Poppins-Regular.ttf",
			weight: "400",
			style: "normal",
		},
	],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={poppins.className}>{children}</body>
		</html>
	);
}
